### PR TITLE
Implement auto-fix

### PR DESCRIPTION
**Pull request by krasnoukhov**
Stole the implementation from here: https://github.com/eslint/eslint/blob/ae51eb24998299a29c5b87c829587e772f6d9a03/lib/rules/no-var.js#L313

Seems to be pretty straightforward. Helps a lot for those who want to migrate! Not sure about the tests though.

### CODE REVIEW

**Comment by cowboyd** [comment]
Thanks Dmitry for this! I agree it would be very helpful. Is there a chance that the `no-var` tests would lend some insight?

**Comment by krasnoukhov** [comment]
@cowboyd Yes thanks for the tip, added the `output` statements so it now checks the replacement was correct. Please note that it's implemented only for const -> let rule, I don't see a reason to implement it for the var -> let rule

**Comment by pzuraq** [comment]
Any movement on this? Would be really useful for us 😄

**Comment by cowboyd** [comment]
@pzuraq @krasnoukhov This looks good, but I do think that we should implement the fixer for `var` as well.

**Comment by krasnoukhov** [comment]
I don't see a reason to duplicate functionality already provided by eslint core

**Comment by cowboyd** [comment]
Oh, I see. Well then should we then remove the check for `var` inside `prefer-let` if this is already taken care of by eslint core?

In other words, just don't trigger a report here https://github.com/cowboyd/eslint-plugin-prefer-let/blob/master/lib/rules/prefer-let.js#L53 ?

**Comment by krasnoukhov** [comment]
Makes sense to me, but don't you think this is out of the scope of this PR?

**Comment by cowboyd** [comment]
I don't know. I feel like merging it in as-is kinda puts the plugin in an inconsistent state.

I assume you're talking about this rule? https://eslint.org/docs/rules/no-var 

Is it possible to have the `prefer-let` rule depend on `no-var`? If so, splitting it out into a separate PR makes sense, and then merge it before this one?

**Comment by krasnoukhov** [comment]
I'm not sure either if this plugin can depend on that other rule. However, I'm wiling to update this PR once other change gets merged

**Comment by stormwarning** [comment]
Is this still a possibility of being merged?

**Comment by cowboyd** [comment]
@stormwarning Yes, I think so. I've been thinking we should propose this rule for eslint core.

**Pull request merged**
